name: Test Build Prod

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU (for ARM emulation)
      uses: docker/setup-qemu-action@v3

    - name: Log in to Dockerhub
      uses: docker/login-action@v3
      with:
        username: thomasmcnamara7
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: thomasmcnamara7/productivity-tool-backend:${{ env.SHORT_SHA }}
        platforms: linux/arm64

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development

    steps:
    - name: Configure AWS credentials
      id: render-task-definition
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Update task definition
      uses: aws=actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition-family: productivity-tool-backend
        container-name: backend-express
        image: thomasmcnamara7/productivity-tool-backend:${{ env.SHORT_SHA }}

    - name: Update ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
        service: productivity-tool-backend-service-rilp874x
        cluster: productivity-tool
  
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: deploy-dev
    environment:
      name: production
    steps:
    - name: Temp
      run: echo "Temporary Step"

